### ISSUE TITLE
Default to VSCode Dark/Light theme

### ISSUE THREAD

**Issue by steven-tey** [BennyKok/novel-vscode#1]
Might wanna default to the VSCode theme (light/dark)	

![CleanShot 2023-09-02 at 09 43 16](https://github.com/BennyKok/novel-vscode/assets/28986134/9b5fd483-d71c-4a3f-aebb-b3b59f0fb74e)

For context the way Novel does it is via CSS variables: https://twitter.com/steventey/status/1677339375645126659

**Comment by BennyKok** [comment]
https://github.com/BennyKok/novel-vscode/assets/18395202/6913c0c5-c341-4c73-957a-f477a247152f

Got it! Was using the same next-theme config but seems like by default it followed system color, i made it listen on vscode's theme changes now!

**Comment by BennyKok** [comment]
Should arrive in v0.2.0!
