### ISSUE TITLE
complie to vsix

### ISSUE THREAD

**Issue by jt6677** [BennyKok/novel-vscode#3]
I spent some time trying to compile it to vsix so I do not have to run it as development locally. I would love to see your compile process since I could not figure out where to run ```vsce package```

**Comment by BennyKok** [comment]
Hey thanks for asking, for packaging, you can do it with `pnpm package`
Also just updated the description about packaging in the README

**Comment by jt6677** [comment]
I tried it with error of ```Manifest needs the 'activationEvents' property, given it has a 'main' property.```

**Comment by jt6677** [comment]
btw,  for folks new to vscode extension like me, they would need ```npm install --global vsce``` .

**Comment by BennyKok** [comment]
interesting, curious if installing from the marketplace works for you? 
I found this, is this when you packaging? https://github.com/microsoft/vscode-vsce/issues/808
what is version of your vsce and vscode?

**Comment by jt6677** [comment]
problem sovled. I used vsce form npm install --global vsce which stops at 2.15.  I should  use ```npm i @vscode/vsce --global```  thank you.

**Comment by jt6677** [comment]
problem sovled. I used vsce form npm install --global vsce which tops at 2.15. I should use ```npm i @vscode/vsce``` --global thank you.
