### ISSUE TITLE
Setting for open markdown files directly in novel

### ISSUE THREAD

**Issue by hakan-akgul** [BennyKok/novel-vscode#6]
Thanks for the great extension  

If there will be an option in settings about opening directly markdown files in novel, it would be great.

**Comment by BennyKok** [comment]
Thanks! It should now by default open as default, which version are you using now?

**Comment by hakan-akgul** [comment]
> Thanks! It should now by default open as default, which version are you using now?

I checked now, it opens by default. Great ✨ 
 
But i mean, if there is a toggle button or setting -i mentioned before- it would be nicer. That's my opinion 😊

**Comment by hakan-akgul** [comment]
v0.3.0
