### ISSUE TITLE
> Thanks! It should now by default open as default, which version are you using now?

### ISSUE THREAD

**Issue by adhituua** [BennyKok/novel-vscode#8]
> Thanks! It should now by default open as default, which version are you using now?

I checked now, it opens by default. Great ✨ 
 
But i mean, if there is a toggle button or setting -i mentioned before- it would be nicer. That's my opinion 😊

_Originally posted by @hakan-akgul in https://github.com/BennyKok/novel-vscode/issues/6#issuecomment-1708907789_

**Comment by BennyKok** [comment]
Its possible now by configuring the default editor, also just updated readme file!
https://github.com/BennyKok/novel-vscode/assets/18395202/27c723a3-64a5-499f-a01f-817687a65ae5

**Comment by hakan-akgul** [comment]
Got it, thanks
